webtalk_init -webtalk_dir D:/Downloads/Mini-Mips32-cc184733fc9d1a1218c955b7371f0dd9f6556d44/MiniMIPS32_board/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jul  4 17:21:48 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3012e5bc-5fb7-4db5-9f08-d2c8f100bfde" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a782599f68554ea298c90a18e49242d0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15400 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8080_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2804662302 -regid "" -xml D:/Downloads/Mini-Mips32-cc184733fc9d1a1218c955b7371f0dd9f6556d44/MiniMIPS32_board/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Downloads/Mini-Mips32-cc184733fc9d1a1218c955b7371f0dd9f6556d44/MiniMIPS32_board/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Downloads/Mini-Mips32-cc184733fc9d1a1218c955b7371f0dd9f6556d44/MiniMIPS32_board/MiniMIPS32.sim/sim_1/behav/xsim/xsim.dir/MiniMIPS32_SYS_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
